### ISSUE TITLE
RelationshipQuerySet does not properly reset its cache

### ISSUE THREAD

**Issue by baconz** [scholrly/neo4django#67]
Take the following example:

```
class Knight(models.NodeModel):
    number_of_limbs = models.IntegerProperty(indexed=True)


class Spam(models.NodeModel):
    VERY_DELICIOUS, NOT_DELICIOUS = 'v', 'n'
    DELICIOUSNESS_CHOICES = (
        ('n', 'not'),
        ('v', 'very'),
    )

    deliciousness = models.StringProperty(max_length=1,
                                      choices=DELICIOUSNESS_CHOICES)
    on_top_of = models.Relationship('Knight', related_name="spams", rel_type=Outgoing.GOES_WITH)

>>> k = Knight.objects.create(number_of_limbs=1)
>>> s = Spam.objects.create(deliciousness=Spam.VERY_DELICIOUS)
>>> s.on_top_of.add(k)
>>> s.save()
>>> len(list(s.on_top_of.all()))
>>> k.delete()
>>> len(list(s.on_top_of.all()))
```

The last command should yield 0, but it will yield 1, because the queryset is still cached.

**Comment by mhluongo** [comment]
@baconz, was this fixed by one of the recent pull requests?

**Comment by baconz** [comment]
Unfortunately, it was not -- this issue still needs to be addressed.
